name: Build & Push SignalX Docker images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

# رقم الإصدار اختياري. لو ما حطّيتش Variable، هيستخدم v11.2 تلقائيًا
env:
  IMAGE_VERSION: ${{ vars.IMAGE_VERSION || 'v11.2' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ===== Backend =====
      - name: Build & Push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/signalx-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/signalx-backend:${{ env.IMAGE_VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/signalx-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/signalx-backend:buildcache,mode=max

      # ===== Frontend (web) =====
      - name: Build & Push web
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/signalx-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/signalx-web:${{ env.IMAGE_VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/signalx-web:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/signalx-web:buildcache,mode=max
